spring:
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${DB_USERNAME}
    hikari:
      schema: ${DB_SCHEMA}
  flyway:
    enabled: true
    schemas: ${DB_SCHEMA}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_SCHEMA}
        jdbc:
          time_zone: UTC
